version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: feature-scene-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: feature-scene-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password123
    depends_on:
      - neo4j
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feature-scene-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  neo4j_data:
  neo4j_logs: