apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-scene-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-scene-frontend
spec:
  replicas: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-scene-ingress
spec:
  rules:
  - host: staging.feature-scene.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: feature-scene-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: feature-scene-frontend
            port:
              number: 80