apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namespace: feature-scene-production

patchesStrategicMerge:
- deployment-patches.yaml

configMapGenerator:
- name: feature-scene-config
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=info
  - BATCH_SCHEDULE_CRON=0 2 * * *

images:
- name: feature-scene-backend
  newTag: v1.0.0
- name: feature-scene-frontend
  newTag: v1.0.0