apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-scene-backend
  labels:
    app: feature-scene
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feature-scene
      component: backend
  template:
    metadata:
      labels:
        app: feature-scene
        component: backend
    spec:
      containers:
      - name: backend
        image: feature-scene-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: NEO4J_URI
          valueFrom:
            secretKeyRef:
              name: feature-scene-secrets
              key: neo4j-uri
        - name: NEO4J_USERNAME
          valueFrom:
            secretKeyRef:
              name: feature-scene-secrets
              key: neo4j-username
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: feature-scene-secrets
              key: neo4j-password
        - name: POSTHOG_API_KEY
          valueFrom:
            secretKeyRef:
              name: feature-scene-secrets
              key: posthog-api-key
        - name: POSTHOG_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: feature-scene-secrets
              key: posthog-project-id
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: feature-scene-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: feature-scene-backend
  labels:
    app: feature-scene
    component: backend
spec:
  selector:
    app: feature-scene
    component: backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP