apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- frontend-deployment.yaml
- neo4j-deployment.yaml
- ingress.yaml

commonLabels:
  app: feature-scene
  
namespace: feature-scene